-- BASELINE MANGKASIR SCHEMAS (POSTGRESQL DIALECT)
CREATE SCHEMA IF NOT EXISTS public;

-- ========================================================
-- 1. DROP EXISTING TABLES CASCADE
-- ========================================================
DROP TABLE IF EXISTS cash_categories CASCADE;
DROP TABLE IF EXISTS cash_periods CASCADE;
DROP TABLE IF EXISTS cash_transactions CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS contact_us CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS districts CASCADE;
DROP TABLE IF EXISTS faqs CASCADE;
DROP TABLE IF EXISTS file_uploads CASCADE;
DROP TABLE IF EXISTS guides CASCADE;
DROP TABLE IF EXISTS otp_verifications CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS product_cats CASCADE;
DROP TABLE IF EXISTS provinces CASCADE;
DROP TABLE IF EXISTS referrals CASCADE;
DROP TABLE IF EXISTS settings CASCADE;
DROP TABLE IF EXISTS stocks CASCADE;
DROP TABLE IF EXISTS stock_in_details CASCADE;
DROP TABLE IF EXISTS stock_in_headers CASCADE;
DROP TABLE IF EXISTS stock_out_details CASCADE;
DROP TABLE IF EXISTS stock_out_headers CASCADE;
DROP TABLE IF EXISTS stores CASCADE;
DROP TABLE IF EXISTS tokens CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS user_data CASCADE;
DROP TABLE IF EXISTS user_has_store CASCADE;
DROP TABLE IF EXISTS villages CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS transaction_details CASCADE;

-- ========================================================
-- 2. CREATE TABLES
-- ========================================================
CREATE TABLE affiliators (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  name varchar(100) NOT NULL,
  phone varchar(20) DEFAULT NULL,
  referral_code varchar(20) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UKl9talc3p8hdeigpjljmm1iofj UNIQUE (referral_code)
);

CREATE TABLE cash_categories (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  name varchar(100) NOT NULL,
  store_id BIGINT NOT NULL,
  type varchar(20) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE cash_periods (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  end_date date NOT NULL,
  start_date date NOT NULL,
  store_id BIGINT NOT NULL,
  transactions_ids text NOT NULL,
  cash_transaction_id BIGINT  DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE cash_transactions (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  debit decimal(15,2) DEFAULT NULL,
  description text DEFAULT NULL,
  kredit decimal(15,2) DEFAULT NULL,
  note text DEFAULT NULL,
  source varchar(255) DEFAULT NULL,
  store_id BIGINT NOT NULL,
  transaction_date date NOT NULL,
  category_id BIGINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE cities (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  code varchar(255) NOT NULL,
  meta text DEFAULT NULL,
  name varchar(255) NOT NULL,
  province_code varchar(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UKqww1g66rmhx352jxut53oqh3y UNIQUE (code)
);

CREATE TABLE contact_us (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  business_name varchar(255) DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  description text DEFAULT NULL,
  name varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE customers (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  address varchar(250) DEFAULT NULL,
  name varchar(100) NOT NULL,
  phone varchar(14) DEFAULT NULL,
  store_id BIGINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE districts (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  code varchar(255) NOT NULL,
  meta text DEFAULT NULL,
  name varchar(255) NOT NULL,
  city_code varchar(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UKgkpvb55aiiyu9n55qoxcwmkds UNIQUE (code)
);

CREATE TABLE faqs (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  description text NOT NULL,
  title varchar(255) DEFAULT NULL,
  category VARCHAR(50) CHECK (category IN ('MOBILE','WEB')) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE file_uploads (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  name varchar(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE guides (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  category VARCHAR(50) CHECK (category IN ('MOBILE','WEB')) NOT NULL,
  description text NOT NULL,
  step_order INTEGER DEFAULT NULL,
  title varchar(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE otp_verifications (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  attemptCount INTEGER NOT NULL,
  email varchar(255) NOT NULL,
  expiresAt TIMESTAMPTZ NOT NULL,
  ipAddress varchar(255) DEFAULT NULL,
  isUsed BOOLEAN NOT NULL,
  otpCode varchar(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UKfpgiit0i40arv0kvwm8gaylwy UNIQUE (email)
);

CREATE TABLE products (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  barcode varchar(255) DEFAULT NULL,
  cost decimal(10,2) NOT NULL,
  guid varchar(255) NOT NULL,
  image varchar(255) DEFAULT NULL,
  name varchar(100) NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  sku varchar(255) DEFAULT NULL,
  store_id BIGINT NOT NULL,
  product_category_id BIGINT DEFAULT NULL,
  parent_id varchar(255) DEFAULT NULL,
  is_stock BOOLEAN NOT NULL DEFAULT FALSE,
  last_stock_sync_at TIMESTAMPTZ DEFAULT NULL,
  qty INTEGER NOT NULL,
  unit varchar(20) DEFAULT NULL,
  is_use_stock BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (id),
  CONSTRAINT UK61e53qqtjxf7l3qav8k2o3fm9 UNIQUE (guid),
  CONSTRAINT UKoie313ijvf9pttp4x7mru4oa3 UNIQUE (store_id,sku)
);

CREATE TABLE product_cats (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  category_name varchar(255) NOT NULL,
  store_id BIGINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE provinces (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  code varchar(255) NOT NULL,
  meta text DEFAULT NULL,
  name varchar(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UKdalikev902uvkpwn632apqe1k UNIQUE (code)
);

CREATE TABLE referrals (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  referral_code varchar(20) NOT NULL,
  referred_user_id BIGINT NOT NULL,
  referrer_affiliator_id BIGINT NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UKb1jxe2jtijo29pbjnvb3cb1g2 UNIQUE (referred_user_id)
);

CREATE TABLE settings (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  meta_key varchar(255) NOT NULL,
  meta_name varchar(255) NOT NULL,
  meta_value varchar(255) NOT NULL,
  store_id BIGINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE stocks (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  product_guid varchar(50) NOT NULL,
  qty INTEGER NOT NULL,
  stock_in_detail_id BIGINT NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UKgyyl8jexq4qhnja1sohj639p8 UNIQUE (stock_in_detail_id)
);

CREATE TABLE stock_in_details (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  batch_number varchar(50) DEFAULT NULL,
  cost decimal(10,2) NOT NULL,
  expiry_date date DEFAULT NULL,
  product_guid varchar(50) NOT NULL,
  product_name varchar(255) DEFAULT NULL,
  qty INTEGER NOT NULL,
  stock_in_header_id BIGINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE stock_in_headers (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  date TIMESTAMPTZ NOT NULL,
  description varchar(500) DEFAULT NULL,
  reference_number varchar(100) DEFAULT NULL,
  store_id BIGINT NOT NULL,
  type varchar(20) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE stock_out_details (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  cost decimal(10,2) NOT NULL,
  product_guid varchar(50) NOT NULL,
  product_name varchar(255) DEFAULT NULL,
  qty INTEGER NOT NULL,
  reason varchar(500) DEFAULT NULL,
  stock_id BIGINT DEFAULT NULL,
  stock_out_header_id BIGINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE stock_out_headers (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  date TIMESTAMPTZ NOT NULL,
  description varchar(500) DEFAULT NULL,
  reference_number varchar(100) DEFAULT NULL,
  store_id BIGINT NOT NULL,
  type varchar(20) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE stores (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  is_active BOOLEAN DEFAULT NULL,
  name varchar(255) NOT NULL,
  phone varchar(255) DEFAULT NULL,
  image varchar(255) DEFAULT NULL,
  currency VARCHAR(50) CHECK (currency IN ('IDR','USD')) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE tokens (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  refreshToken varchar(255) DEFAULT NULL,
  revoked BOOLEAN NOT NULL,
  userAgent varchar(255) DEFAULT NULL,
  user_id BIGINT DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE users (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  email varchar(100) NOT NULL,
  is_active BOOLEAN DEFAULT NULL,
  is_verified BOOLEAN DEFAULT NULL,
  password varchar(255) NOT NULL,
  profile_path varchar(255) DEFAULT NULL,
  role VARCHAR(50) CHECK (role IN ('Administrator','Kasir','Owner')) DEFAULT NULL,
  user_token varchar(255) DEFAULT NULL,
  username varchar(100) NOT NULL,
  user_data_id BIGINT DEFAULT NULL,
  isEmailVerified BOOLEAN NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UK6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
  CONSTRAINT UKr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
  CONSTRAINT UK7a849kccj7lwk5od479xdcp38 UNIQUE (user_data_id)
);

CREATE TABLE user_data (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  address varchar(200) DEFAULT NULL,
  city varchar(50) DEFAULT NULL,
  date_of_birth TIMESTAMPTZ DEFAULT NULL,
  district varchar(50) DEFAULT NULL,
  email varchar(100) NOT NULL,
  full_name varchar(100) NOT NULL,
  is_verified BOOLEAN DEFAULT NULL,
  phone varchar(20) DEFAULT NULL,
  place_of_birth varchar(50) DEFAULT NULL,
  provice varchar(50) DEFAULT NULL,
  village varchar(50) DEFAULT NULL,
  image varchar(255) DEFAULT NULL,
  village_code varchar(255) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UKdhxuydjj5l1vds6s9eex23dcr UNIQUE (email)
);

CREATE TABLE user_has_store (
  user_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL
);

CREATE TABLE villages (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  code varchar(255) NOT NULL,
  meta text DEFAULT NULL,
  name varchar(255) NOT NULL,
  district_code varchar(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UKmf99e00e17ph6wpbs8sqskp6j UNIQUE (code)
);

CREATE TABLE payments (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  change_amount DOUBLE PRECISION DEFAULT NULL,
  date TIMESTAMPTZ DEFAULT NULL,
  guid varchar(255) DEFAULT NULL,
  notes varchar(300) DEFAULT NULL,
  paid DOUBLE PRECISION DEFAULT NULL,
  payment_methode varchar(255) DEFAULT NULL,
  sub_total DOUBLE PRECISION DEFAULT NULL,
  transaction_guid varchar(255) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UKrgqxn64fojs5a58anfn3p0l UNIQUE (guid)
);

CREATE TABLE transactions (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  customer_name varchar(255) DEFAULT NULL,
  customer_id BIGINT DEFAULT NULL,
  date TIMESTAMPTZ DEFAULT NULL,
  guid varchar(255) DEFAULT NULL,
  invoice varchar(255) DEFAULT NULL,
  invoice_discount DOUBLE PRECISION DEFAULT NULL,
  invoice_ppn DOUBLE PRECISION DEFAULT NULL,
  store_id INTEGER DEFAULT NULL,
  sub_total DOUBLE PRECISION DEFAULT NULL,
  flag varchar(20) NOT NULL DEFAULT 'done',
  PRIMARY KEY (id),
  CONSTRAINT UKrbkybdprqkd4nc0r6ps5gunr UNIQUE (guid),
  CONSTRAINT UKpf7esdu07le5j38c15b7kv997 UNIQUE (invoice)
);

CREATE TABLE transaction_details (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  createdAt TIMESTAMPTZ DEFAULT NULL,
  createdBy varchar(255) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMPTZ DEFAULT NULL,
  updatedBy varchar(255) DEFAULT NULL,
  discount DOUBLE PRECISION DEFAULT NULL,
  ppn DOUBLE PRECISION DEFAULT NULL,
  price DOUBLE PRECISION DEFAULT NULL,
  product_guid varchar(255) DEFAULT NULL,
  product_name varchar(255) DEFAULT NULL,
  product_sku varchar(255) DEFAULT NULL,
  qty INTEGER DEFAULT NULL,
  total_price DOUBLE PRECISION DEFAULT NULL,
  transaction_guid varchar(255) DEFAULT NULL,
  cost decimal(10,2) NOT NULL,
  stock_in_id BIGINT DEFAULT NULL,
  PRIMARY KEY (id)
);


-- ========================================================
-- 3. CREATE INDICES
-- ========================================================
CREATE INDEX IF NOT EXISTS IDXl9talc3p8hdeigpjljmm1iofj ON public.affiliators (referral_code);
CREATE INDEX IF NOT EXISTS idx_cash_categories_store_id ON public.cash_categories (store_id);
CREATE INDEX IF NOT EXISTS idx_cash_categories_store_deleted ON public.cash_categories (store_id,deleted);
CREATE INDEX IF NOT EXISTS idx_cash_periods_store_date ON public.cash_periods (store_id,start_date,end_date);
CREATE INDEX IF NOT EXISTS idx_cash_periods_store_deleted ON public.cash_periods (store_id,deleted);
CREATE INDEX IF NOT EXISTS idx_cash_transactions_store_date ON public.cash_transactions (store_id,transaction_date);
CREATE INDEX IF NOT EXISTS idx_cash_transactions_store_deleted ON public.cash_transactions (store_id,deleted);
CREATE INDEX IF NOT EXISTS idx_cash_transactions_category ON public.cash_transactions (category_id);
CREATE INDEX IF NOT EXISTS province_code ON public.cities (province_code);
CREATE INDEX IF NOT EXISTS FKfo2nbino9sutm98o6hbac74ue ON public.customers (store_id);
CREATE INDEX IF NOT EXISTS FK4851qs7qegiujcq093f8hdlih ON public.districts (city_code);
CREATE INDEX IF NOT EXISTS FK6owcuvsxh28icwrbnpubn1ykj ON public.products (product_category_id);
CREATE INDEX IF NOT EXISTS FKtg6wn5mwlsrvgrm09gds7leox ON public.products (parent_id);
CREATE INDEX IF NOT EXISTS FK3gnvfqox8uod6n7vhhlge0lce ON public.referrals (referrer_affiliator_id);
CREATE INDEX IF NOT EXISTS FKmnsm95blhmn8yxjlwoasftxpi ON public.settings (store_id);
CREATE INDEX IF NOT EXISTS idx_stocks_product_created ON public.stocks (product_guid,createdAt);
CREATE INDEX IF NOT EXISTS FKariwfcrb1v2kdfd0gfs4km2p0 ON public.stock_in_details (stock_in_header_id);
CREATE INDEX IF NOT EXISTS FK71lp6hdkyk6xr4b869ex4g5fg ON public.stock_out_details (stock_id);
CREATE INDEX IF NOT EXISTS FKaychye6n47rd2l68obho5kfw3 ON public.stock_out_details (stock_out_header_id);
CREATE INDEX IF NOT EXISTS FK2dylsfo39lgjyqml2tbe0b0ss ON public.tokens (user_id);
CREATE INDEX IF NOT EXISTS village_code ON public.user_data (village_code);
CREATE INDEX IF NOT EXISTS FK6qiqxoom5n1caybxysjpwqc0i ON public.user_has_store (store_id);
CREATE INDEX IF NOT EXISTS FKba463r99mupsplme2dxrkn1ds ON public.user_has_store (user_id);
CREATE INDEX IF NOT EXISTS FK1kbctl5s9tgap8yinl37nsb3n ON public.villages (district_code);
CREATE INDEX IF NOT EXISTS FKcdww9prd1q98yvhwiy2qpkjfx ON public.payments (transaction_guid);
CREATE INDEX IF NOT EXISTS FKf457qf5ukdmtrnooa3080komw ON public.transaction_details (transaction_guid);

-- ========================================================
-- 4. CREATE FOREIGN KEY CONSTRAINTS
-- ========================================================
ALTER TABLE public.cash_transactions ADD CONSTRAINT FKngag8gntxjmswsvvj94wi1wso FOREIGN KEY (category_id) REFERENCES public.cash_categories (id) ;
ALTER TABLE public.cities ADD CONSTRAINT province_code FOREIGN KEY (province_code) REFERENCES public.provinces (code) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public.customers ADD CONSTRAINT FKfo2nbino9sutm98o6hbac74ue FOREIGN KEY (store_id) REFERENCES public.stores (id) ;
ALTER TABLE public.districts ADD CONSTRAINT FK4851qs7qegiujcq093f8hdlih FOREIGN KEY (city_code) REFERENCES public.cities (code) ;
ALTER TABLE public.products ADD CONSTRAINT FK6owcuvsxh28icwrbnpubn1ykj FOREIGN KEY (product_category_id) REFERENCES public.product_cats (id) ;
ALTER TABLE public.products ADD CONSTRAINT FKtg6wn5mwlsrvgrm09gds7leox FOREIGN KEY (parent_id) REFERENCES public.products (guid) ;
ALTER TABLE public.referrals ADD CONSTRAINT FK3gnvfqox8uod6n7vhhlge0lce FOREIGN KEY (referrer_affiliator_id) REFERENCES public.affiliators (id) ;
ALTER TABLE public.referrals ADD CONSTRAINT FKj2olu4j15ay3h74kaycue2ptx FOREIGN KEY (referred_user_id) REFERENCES public.users (id) ;
ALTER TABLE public.settings ADD CONSTRAINT FKmnsm95blhmn8yxjlwoasftxpi FOREIGN KEY (store_id) REFERENCES public.stores (id) ;
ALTER TABLE public.stocks ADD CONSTRAINT FKdijuytuiujr2wsyfno5o631oo FOREIGN KEY (stock_in_detail_id) REFERENCES public.stock_in_details (id) ;
ALTER TABLE public.stock_in_details ADD CONSTRAINT FKariwfcrb1v2kdfd0gfs4km2p0 FOREIGN KEY (stock_in_header_id) REFERENCES public.stock_in_headers (id) ;
ALTER TABLE public.stock_out_details ADD CONSTRAINT FK71lp6hdkyk6xr4b869ex4g5fg FOREIGN KEY (stock_id) REFERENCES public.stocks (id) ;
ALTER TABLE public.stock_out_details ADD CONSTRAINT FKaychye6n47rd2l68obho5kfw3 FOREIGN KEY (stock_out_header_id) REFERENCES public.stock_out_headers (id) ;
ALTER TABLE public.tokens ADD CONSTRAINT FK2dylsfo39lgjyqml2tbe0b0ss FOREIGN KEY (user_id) REFERENCES public.users (id) ;
ALTER TABLE public.users ADD CONSTRAINT FKakgvxgowqbd2cuhfyx2kyfu0u FOREIGN KEY (user_data_id) REFERENCES public.user_data (id) ;
ALTER TABLE public.user_data ADD CONSTRAINT village_code FOREIGN KEY (village_code) REFERENCES public.villages (code) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public.user_has_store ADD CONSTRAINT FK6qiqxoom5n1caybxysjpwqc0i FOREIGN KEY (store_id) REFERENCES public.stores (id) ;
ALTER TABLE public.user_has_store ADD CONSTRAINT FKba463r99mupsplme2dxrkn1ds FOREIGN KEY (user_id) REFERENCES public.users (id) ;
ALTER TABLE public.villages ADD CONSTRAINT FK1kbctl5s9tgap8yinl37nsb3n FOREIGN KEY (district_code) REFERENCES public.districts (code) ;
ALTER TABLE public.payments ADD CONSTRAINT FKcdww9prd1q98yvhwiy2qpkjfx FOREIGN KEY (transaction_guid) REFERENCES public.transactions (guid) ;
ALTER TABLE public.transaction_details ADD CONSTRAINT FKf457qf5ukdmtrnooa3080komw FOREIGN KEY (transaction_guid) REFERENCES public.transactions (guid) ;